platform:ios,'4.3'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'ViewDeck', '~> 2.2.5'
pod 'AFNetworking', '~> 0.10.x'
pod 'SDWebImage', '~> 2.7.4'
pod 'MWPhotoBrowser', '~> 1.0.1'
pod 'VPPDropDown', '~> 0.3.0'
pod 'TPKeyboardAvoiding'