platform:ios,'5.0'
pod 'JSONKit',       '~> 1.4'
pod 'Reachability',  '~> 3.0.0'
pod 'AFNetworking', '~> 0.10.x'
pod 'SDWebImage', '~> 2.7.4'
pod 'TPKeyboardAvoiding'
pod 'ECSlidingViewController'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'